// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApL-S_4_7GE5_hjRnGk_NY8t_54Rxzhe4',
    appId: '1:5961427189:web:da0a8819b2a91ffd477dbc',
    messagingSenderId: '5961427189',
    projectId: 'automaat-777f0',
    authDomain: 'automaat-777f0.firebaseapp.com',
    storageBucket: 'automaat-777f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm32paGIrxjHKXkeHmQYASdfC4XFfEzZk',
    appId: '1:5961427189:android:09fb391f1e1378ac477dbc',
    messagingSenderId: '5961427189',
    projectId: 'automaat-777f0',
    storageBucket: 'automaat-777f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO39sjnn4wpa0Fgbd25S-xLA9OznQ01lg',
    appId: '1:5961427189:ios:bc00e13e80eebee5477dbc',
    messagingSenderId: '5961427189',
    projectId: 'automaat-777f0',
    storageBucket: 'automaat-777f0.firebasestorage.app',
    iosBundleId: 'com.example.automaat',
  );
}
